// Code generated by protoc-gen-golite. DO NOT EDIT.
// source: NTV2RichMedia.proto

package richmedia

import (
	proto "github.com/RomiChan/protobuf/proto"
)

type NTV2RichMediaReq struct {
	ReqHead          *MultiMediaReqHead   `protobuf:"bytes,1,opt"`
	Upload           *UploadReq           `protobuf:"bytes,2,opt"`
	Download         *DownloadReq         `protobuf:"bytes,3,opt"`
	DownloadRKey     *DownloadRKeyReq     `protobuf:"bytes,4,opt"`
	Delete           *DeleteReq           `protobuf:"bytes,5,opt"`
	UploadCompleted  *UploadCompletedReq  `protobuf:"bytes,6,opt"`
	MsgInfoAuth      *MsgInfoAuthReq      `protobuf:"bytes,7,opt"`
	UploadKeyRenewal *UploadKeyRenewalReq `protobuf:"bytes,8,opt"`
	DownloadSafe     *DownloadSafeReq     `protobuf:"bytes,9,opt"`
	Extension        []byte               `protobuf:"bytes,99,opt"`
}

type MultiMediaReqHead struct {
	Common *CommonHead `protobuf:"bytes,1,opt"`
	Scene  *SceneInfo  `protobuf:"bytes,2,opt"`
	Client *ClientMeta `protobuf:"bytes,3,opt"`
	_      [0]func()
}

type CommonHead struct {
	RequestId uint32 `protobuf:"varint,1,opt"` // 1
	Command   uint32 `protobuf:"varint,2,opt"` // 200
	_         [0]func()
}

type SceneInfo struct {
	RequestType  uint32       `protobuf:"varint,101,opt"` // 1
	BusinessType uint32       `protobuf:"varint,102,opt"` // 3
	SceneType    uint32       `protobuf:"varint,200,opt"` // 1
	C2C          *C2CUserInfo `protobuf:"bytes,201,opt"`
	Group        *NTGroupInfo `protobuf:"bytes,202,opt"`
	_            [0]func()
}

type C2CUserInfo struct {
	AccountType uint32 `protobuf:"varint,1,opt"` // 2
	TargetUid   string `protobuf:"bytes,2,opt"`
	_           [0]func()
}

type NTGroupInfo struct {
	GroupUin uint32 `protobuf:"varint,1,opt"`
	_        [0]func()
}

type ClientMeta struct {
	AgentType uint32 `protobuf:"varint,1,opt"` // 2
	_         [0]func()
}

type DownloadReq struct {
	Node     *IndexNode   `protobuf:"bytes,1,opt"`
	Download *DownloadExt `protobuf:"bytes,2,opt"`
	_        [0]func()
}

type IndexNode struct {
	Info       *FileInfo `protobuf:"bytes,1,opt"`
	FileUuid   string    `protobuf:"bytes,2,opt"`
	StoreId    uint32    `protobuf:"varint,3,opt"` // 0旧服务器 1为nt服务器
	UploadTime uint32    `protobuf:"varint,4,opt"` // 0
	Ttl        uint32    `protobuf:"varint,5,opt"` // 0
	SubType    uint32    `protobuf:"varint,6,opt"` // 0
	_          [0]func()
}

type FileInfo struct {
	FileSize uint32    `protobuf:"varint,1,opt"` // 0
	FileHash string    `protobuf:"bytes,2,opt"`
	FileSha1 string    `protobuf:"bytes,3,opt"` // ""
	FileName string    `protobuf:"bytes,4,opt"`
	Type     *FileType `protobuf:"bytes,5,opt"`
	Width    uint32    `protobuf:"varint,6,opt"` // 0
	Height   uint32    `protobuf:"varint,7,opt"` // 0
	Time     uint32    `protobuf:"varint,8,opt"` // 2
	Original uint32    `protobuf:"varint,9,opt"` // 0
	_        [0]func()
}

type FileType struct {
	Type        uint32 `protobuf:"varint,1,opt"` // 2
	PicFormat   uint32 `protobuf:"varint,2,opt"` // 0
	VideoFormat uint32 `protobuf:"varint,3,opt"` // 0
	VoiceFormat uint32 `protobuf:"varint,4,opt"` // 1
	_           [0]func()
}

type DownloadExt struct {
	Pic   *PicDownloadExt   `protobuf:"bytes,1,opt"`
	Video *VideoDownloadExt `protobuf:"bytes,2,opt"`
	Ptt   *PttDownloadExt   `protobuf:"bytes,3,opt"`
	_     [0]func()
}

type VideoDownloadExt struct {
	BusiType    uint32 `protobuf:"varint,1,opt"` // 0
	SceneType   uint32 `protobuf:"varint,2,opt"` // 0
	SubBusiType uint32 `protobuf:"varint,3,opt"` // 0
	_           [0]func()
}

type PicDownloadExt struct {
	_ [0]func()
}

type PttDownloadExt struct {
	_ [0]func()
}

type PicUrlExtInfo struct {
	OriginalParameter string `protobuf:"bytes,1,opt"`
	BigParameter      string `protobuf:"bytes,2,opt"`
	ThumbParameter    string `protobuf:"bytes,3,opt"`
	_                 [0]func()
}

type VideoExtInfo struct {
	VideoCodecFormat uint32 `protobuf:"varint,1,opt"`
	_                [0]func()
}

type MsgInfo struct {
	MsgInfoBody []*MsgInfoBody `protobuf:"bytes,1,rep"`
	ExtBizInfo  *ExtBizInfo    `protobuf:"bytes,2,opt"`
}

type MsgInfoBody struct {
	Index     *IndexNode   `protobuf:"bytes,1,opt"`
	Picture   *PictureInfo `protobuf:"bytes,2,opt"`
	Video     *VideoInfo   `protobuf:"bytes,3,opt"`
	Audio     *AudioInfo   `protobuf:"bytes,4,opt"`
	FileExist bool         `protobuf:"varint,5,opt"`
	HashSum   []byte       `protobuf:"bytes,6,opt"`
}

type VideoInfo struct {
	_ [0]func()
}

type AudioInfo struct {
	_ [0]func()
}

type PictureInfo struct {
	UrlPath string         `protobuf:"bytes,1,opt"`
	Ext     *PicUrlExtInfo `protobuf:"bytes,2,opt"`
	Domain  string         `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type ExtBizInfo struct {
	Pic      *PicExtBizInfo   `protobuf:"bytes,1,opt"`
	Video    *VideoExtBizInfo `protobuf:"bytes,2,opt"`
	Ptt      *PttExtBizInfo   `protobuf:"bytes,3,opt"`
	BusiType uint32           `protobuf:"varint,10,opt"`
	_        [0]func()
}

type PttExtBizInfo struct {
	SrcUin            uint64 `protobuf:"varint,1,opt"`
	PttScene          uint32 `protobuf:"varint,2,opt"`
	PttType           uint32 `protobuf:"varint,3,opt"`
	ChangeVoice       uint32 `protobuf:"varint,4,opt"`
	Waveform          []byte `protobuf:"bytes,5,opt"`
	AutoConvertText   uint32 `protobuf:"varint,6,opt"`
	BytesReserve      []byte `protobuf:"bytes,11,opt"`
	BytesPbReserve    []byte `protobuf:"bytes,12,opt"`
	BytesGeneralFlags []byte `protobuf:"bytes,13,opt"`
}

type VideoExtBizInfo struct {
	FromScene      uint32 `protobuf:"varint,1,opt"`
	ToScene        uint32 `protobuf:"varint,2,opt"`
	BytesPbReserve []byte `protobuf:"bytes,3,opt"`
}

type PicExtBizInfo struct {
	BizType             uint32 `protobuf:"varint,1,opt"`
	TextSummary         string `protobuf:"bytes,2,opt"`
	BytesPbReserveC2C   []byte `protobuf:"bytes,11,opt"`
	BytesPbReserveTroop []byte `protobuf:"bytes,12,opt"`
	FromScene           uint32 `protobuf:"varint,1001,opt"`
	ToScene             uint32 `protobuf:"varint,1002,opt"`
	OldFileId           uint32 `protobuf:"varint,1003,opt"`
}

type DownloadSafeReq struct {
	Index *IndexNode `protobuf:"bytes,1,opt"`
	_     [0]func()
}

type UploadKeyRenewalReq struct {
	OldUKey string `protobuf:"bytes,1,opt"`
	SubType uint32 `protobuf:"varint,2,opt"`
	_       [0]func()
}

type MsgInfoAuthReq struct {
	Msg      []byte `protobuf:"bytes,1,opt"`
	AuthTime uint64 `protobuf:"varint,2,opt"`
}

type UploadCompletedReq struct {
	SrvSendMsg     bool     `protobuf:"varint,1,opt"`
	ClientRandomId uint64   `protobuf:"varint,2,opt"`
	MsgInfo        *MsgInfo `protobuf:"bytes,3,opt"`
	ClientSeq      uint32   `protobuf:"varint,4,opt"`
	_              [0]func()
}

type DeleteReq struct {
	Index         []*IndexNode `protobuf:"bytes,1,rep"`
	NeedRecallMsg bool         `protobuf:"varint,2,opt"`
	MsgSeq        uint64       `protobuf:"varint,3,opt"`
	MsgRandom     uint64       `protobuf:"varint,4,opt"`
	MsgTime       uint64       `protobuf:"varint,5,opt"`
}

type DownloadRKeyReq struct {
	Types []int32 `protobuf:"varint,1,rep"`
}

type UploadInfo struct {
	FileInfo    *FileInfo `protobuf:"bytes,1,opt"`
	SubFileType uint32    `protobuf:"varint,2,opt"`
	_           [0]func()
}

type UploadReq struct {
	UploadInfo             []*UploadInfo `protobuf:"bytes,1,rep"`
	TryFastUploadCompleted bool          `protobuf:"varint,2,opt"`
	SrvSendMsg             bool          `protobuf:"varint,3,opt"`
	ClientRandomId         uint64        `protobuf:"varint,4,opt"`
	CompatQMsgSceneType    uint32        `protobuf:"varint,5,opt"`
	ExtBizInfo             *ExtBizInfo   `protobuf:"bytes,6,opt"`
	ClientSeq              uint32        `protobuf:"varint,7,opt"`
	NoNeedCompatMsg        bool          `protobuf:"varint,8,opt"`
}

type NTV2RichMediaResp struct {
	RespHead         *MultiMediaRespHead   `protobuf:"bytes,1,opt"`
	Upload           *UploadResp           `protobuf:"bytes,2,opt"`
	Download         *DownloadResp         `protobuf:"bytes,3,opt"`
	DownloadRKey     *DownloadRKeyResp     `protobuf:"bytes,4,opt"`
	Delete           *DeleteResp           `protobuf:"bytes,5,opt"`
	UploadCompleted  *UploadCompletedResp  `protobuf:"bytes,6,opt"`
	MsgInfoAuth      *MsgInfoAuthResp      `protobuf:"bytes,7,opt"`
	UploadKeyRenewal *UploadKeyRenewalResp `protobuf:"bytes,8,opt"`
	DownloadSafe     *DownloadSafeResp     `protobuf:"bytes,9,opt"`
	Extension        []byte                `protobuf:"bytes,99,opt"`
}

type MultiMediaRespHead struct {
	Common  *CommonHead `protobuf:"bytes,1,opt"`
	RetCode uint32      `protobuf:"varint,2,opt"`
	Message string      `protobuf:"bytes,3,opt"`
	_       [0]func()
}

type DownloadResp struct {
	RKeyParam      string        `protobuf:"bytes,1,opt"`
	RKeyTtlSecond  uint32        `protobuf:"varint,2,opt"`
	Info           *DownloadInfo `protobuf:"bytes,3,opt"`
	RKeyCreateTime uint32        `protobuf:"varint,4,opt"`
	_              [0]func()
}

type DownloadInfo struct {
	Domain        string         `protobuf:"bytes,1,opt"`
	UrlPath       string         `protobuf:"bytes,2,opt"`
	HttpsPort     uint32         `protobuf:"varint,3,opt"`
	IPv4S         []*IPv4        `protobuf:"bytes,4,rep"`
	IPv6S         []*IPv6        `protobuf:"bytes,5,rep"`
	PicUrlExtInfo *PicUrlExtInfo `protobuf:"bytes,6,opt"`
	VideoExtInfo  *VideoExtInfo  `protobuf:"bytes,7,opt"`
}

type IPv4 struct {
	OutIP   uint32 `protobuf:"varint,1,opt"`
	OutPort uint32 `protobuf:"varint,2,opt"`
	InIP    uint32 `protobuf:"varint,3,opt"`
	InPort  uint32 `protobuf:"varint,4,opt"`
	IPType  uint32 `protobuf:"varint,5,opt"`
	_       [0]func()
}

type IPv6 struct {
	OutIP   []byte `protobuf:"bytes,1,opt"`
	OutPort uint32 `protobuf:"varint,2,opt"`
	InIP    []byte `protobuf:"bytes,3,opt"`
	InPort  uint32 `protobuf:"varint,4,opt"`
	IPType  uint32 `protobuf:"varint,5,opt"`
}

type UploadResp struct {
	UKey          proto.Option[string]         `protobuf:"bytes,1,opt"`
	UKeyTtlSecond uint32                       `protobuf:"varint,2,opt"`
	IPv4S         []*IPv4                      `protobuf:"bytes,3,rep"`
	IPv6S         []*IPv6                      `protobuf:"bytes,4,rep"`
	MsgSeq        uint64                       `protobuf:"varint,5,opt"`
	MsgInfo       *MsgInfo                     `protobuf:"bytes,6,opt"`
	Ext           []*RichMediaStorageTransInfo `protobuf:"bytes,7,rep"`
	CompatQMsg    []byte                       `protobuf:"bytes,8,opt"`
	SubFileInfos  []*SubFileInfo               `protobuf:"bytes,10,rep"`
}

type RichMediaStorageTransInfo struct {
	SubType  uint32 `protobuf:"varint,1,opt"`
	ExtType  uint32 `protobuf:"varint,2,opt"`
	ExtValue []byte `protobuf:"bytes,3,opt"`
}

type SubFileInfo struct {
	SubType       uint32  `protobuf:"varint,1,opt"`
	UKey          string  `protobuf:"bytes,2,opt"`
	UKeyTtlSecond uint32  `protobuf:"varint,3,opt"`
	IPv4S         []*IPv4 `protobuf:"bytes,4,rep"`
	IPv6S         []*IPv6 `protobuf:"bytes,5,rep"`
}

type DownloadSafeResp struct {
	_ [0]func()
}

type UploadKeyRenewalResp struct {
	Ukey       string `protobuf:"bytes,1,opt"`
	UkeyTtlSec uint64 `protobuf:"varint,2,opt"`
	_          [0]func()
}

type MsgInfoAuthResp struct {
	AuthCode   uint32 `protobuf:"varint,1,opt"`
	Msg        []byte `protobuf:"bytes,2,opt"`
	ResultTime uint64 `protobuf:"varint,3,opt"`
}

type UploadCompletedResp struct {
	MsgSeq uint64 `protobuf:"varint,1,opt"`
	_      [0]func()
}

type DeleteResp struct {
	_ [0]func()
}

type DownloadRKeyResp struct {
	RKeys []*RKeyInfo `protobuf:"bytes,1,rep"`
}

type RKeyInfo struct {
	Rkey           string               `protobuf:"bytes,1,opt"`
	RkeyTtlSec     uint64               `protobuf:"varint,2,opt"`
	StoreId        uint32               `protobuf:"varint,3,opt"`
	RkeyCreateTime proto.Option[uint32] `protobuf:"varint,4,opt"`
	Type           proto.Option[uint32] `protobuf:"varint,5,opt"`
	_              [0]func()
}
